# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 06:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20171128_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('column',)},
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 28, 6, 26, 25, 171580, tzinfo=utc)),
        ),
    ]
